import json
import random
import requests
import paho.mqtt.client as mqtt

# Cache generated by k8s_watcher.py
CACHE_FILE = "/home/pi/ingress_cache.json"


# Ryu REST API
RYU_URL = "http://127.0.0.1:8080/routing"


# MQTT settings
MQTT_BROKER = "0.0.0.0"
MQTT_TOPIC = "sensors/#"


service_cache = {}


def load_cache():

    global service_cache

    try:

        with open(CACHE_FILE, "r") as file:

            service_cache = json.load(file)

        print("\nUpdated ingress cache")

        print(json.dumps(service_cache, indent=4))

    except Exception as e:

        print("Cannot load ingress cache:", e)


def select_ingress(sensor):

    if sensor not in service_cache:

        print("No ingress for service:", sensor)

        return None

    available_nodes = service_cache[sensor]

    if len(available_nodes) == 0:

        return None

    #
    # Current selection method:
    # random load distribution
    #
    selected = random.choice(available_nodes)

    print("Available ingress nodes:")

    for node in available_nodes:

        print(node["node"], node["ip"])

    return selected["ip"]


def send_to_ryu(sensor, destination_ip):

    payload = {"sensor": sensor, "destination_ip": destination_ip}

    print("Sending to Ryu:", payload)

    try:

        response = requests.post(RYU_URL, json=payload, timeout=2)

        print("Ryu response:", response.text)

    except Exception as e:

        print("Ryu communication error:", e)


def on_message(client, userdata, msg):

    try:

        topic = msg.topic

        #
        # Example:
        # sensors/bmp280
        #
        sensor = topic.split("/")[1]

        data = json.loads(msg.payload.decode())

        print("\n==============")

        print("Sensor:", sensor)

        print("Data:", data)

        #
        # Reload cache before decision
        #
        # If new node joins,
        # watcher updates file
        #
        load_cache()

        ingress_ip = select_ingress(sensor)

        if ingress_ip is None:

            print("No route available")

            return

        print("Selected ingress:", ingress_ip)

        send_to_ryu(sensor, ingress_ip)

    except Exception as e:

        print("MQTT processing error:", e)


mqtt_client = mqtt.Client()


mqtt_client.on_message = on_message


mqtt_client.connect(MQTT_BROKER, 1883)


mqtt_client.subscribe(MQTT_TOPIC)


print("Dynamic SDN ingress routing started")


mqtt_client.loop_forever()
